#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.3.2f1_b3c100a4b73a"
#define UNITY_VERSION_FULL_NICE "2018.3.2f1 (b3c100a4b73a)"
#define UNITY_VERSION_BLD 11780352
#define UNITY_VERSION_DATE 1547043673
#define UNITY_VERSION_WIN "2018.3.2.11780352"
#define UNITY_VERSION_BRANCH "2018.3/staging"
